package ca.hojat.gamehub.core.data.games.datastores

import ca.hojat.gamehub.core.data.database.games.entities.DbLikedGame
import ca.hojat.gamehub.core.providers.TimestampProvider
import com.paulrybitskyi.hiltbinder.BindType
import javax.inject.Inject
import javax.inject.Singleton

private const val ENTITY_AUTOGENERATED_ID_INDICATOR = 0

interface LikedGameFactory {
    fun createLikedGame(gameId: Int): DbLikedGame
}

@Singleton
@BindType
class LikedGameFactoryImpl @Inject constructor(
    private val timestampProvider: TimestampProvider,
) : LikedGameFactory {

    override fun createLikedGame(gameId: Int): DbLikedGame {
        return DbLikedGame(
            id = ENTITY_AUTOGENERATED_ID_INDICATOR,
            gameId = gameId,
            likeTimestamp = timestampProvider.getUnixTimestamp()
        )
    }
}
