name: Run lint checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: thyrlian/android-sdk:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Run detekt
        run: |
          cd SimpleLogin/
          ./gradlew detekt

